name: pubchem_smirk_gpe_v1024_mb_size700k
kind: smirk_gpe
vocab_size: 1024
min_frequency: 2
corpus: pubchem
training_input: data/processed/pubchem/canon_dedup_v1_extras/size_700k
output_dir: artifacts/tokenizer/pubchem/pubchem_smirk_gpe_v1024_mb_size700k
ref_artifact_dir: null
merge_brackets: true
split_structure: true
seed_size: null
max_piece_length: null
n_sub_iterations: null
shrinking_factor: null
scaffold_log: false
