name: zinc22_smirk_gpe_v1024_nmb_size700k
kind: smirk_gpe
vocab_size: 1024
min_frequency: 2
corpus: zinc22
training_input: data/processed/zinc22/canon_dedup_v1_extras/size_700k
output_dir: artifacts/tokenizer/zinc22/zinc22_smirk_gpe_v1024_nmb_size700k
ref_artifact_dir: null
merge_brackets: false
split_structure: true
seed_size: null
max_piece_length: null
n_sub_iterations: null
shrinking_factor: null
scaffold_log: false
