name: smirk_gpe_v1024_nmb
base_kind: smirk_gpe
vocab_size: 1026
training_corpus_sha: 2604e603ded8e77654016cd7b3f38cec
n_merges: 867
merge_brackets: false
split_structure: true
seed_size: null
max_piece_length: null
n_sub_iterations: null
shrinking_factor: null
scaffold_log_sha: 6550f46d20164934b1b4dd12ee759236354861a34765f2a6090898794228d335
