name: smirk_gpe_v512_nmb
base_kind: smirk_gpe
vocab_size: 514
training_corpus_sha: 2604e603ded8e77654016cd7b3f38cec
n_merges: 355
merge_brackets: false
split_structure: true
seed_size: null
max_piece_length: null
n_sub_iterations: null
shrinking_factor: null
scaffold_log_sha: 17234a8858a57b112489c0b3413a24557a1ca1eb2c15d54bcfa9628b7cc2752b
