name: smirk_gpe_v256_mb
base_kind: smirk_gpe
vocab_size: 258
training_corpus_sha: d471aba7d34c2d2875e958d3df2abfcc
n_merges: 99
merge_brackets: true
split_structure: true
seed_size: null
max_piece_length: null
n_sub_iterations: null
shrinking_factor: null
scaffold_log_sha: fa5fd6450b8a1b5eba2d48b7d49bc07ff9b35538fb05f23fb303d83958e3fbc3
